#!/bin/bash

workspaces=("main" "terminal" "google" "quick_control" "config")

bash "/home/svovoniks/.config/i3/scripts/tmux_init"

for i in ${!workspaces[*]}
do
    i3-msg "workspace $((${i}+1))"
    bash "/home/svovoniks/.config/i3/scripts/${workspaces[${i}]}"
    sleep 0.5
done

i3-msg "workspace 1"
